# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(648, 492)
        self.importBtm = QtWidgets.QPushButton(Dialog)
        self.importBtm.setGeometry(QtCore.QRect(170, 40, 321, 41))
        self.importBtm.setObjectName("importBtm")
        self.runBtm = QtWidgets.QPushButton(Dialog)
        self.runBtm.setGeometry(QtCore.QRect(170, 380, 321, 71))
        self.runBtm.setObjectName("runBtm")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(300, 130, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(300, 210, 61, 20))
        self.label_2.setObjectName("label_2")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setGeometry(QtCore.QRect(140, 170, 391, 20))
        self.nameLabel.setText("")
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.pathLabel = QtWidgets.QLabel(Dialog)
        self.pathLabel.setGeometry(QtCore.QRect(100, 240, 451, 20))
        self.pathLabel.setText("")
        self.pathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pathLabel.setObjectName("pathLabel")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(220, 320, 71, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(300, 320, 71, 20))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.importBtm.setText(_translate("Dialog", "Inport file"))
        self.runBtm.setText(_translate("Dialog", "Glich this!"))
        self.label.setText(_translate("Dialog", "Filename"))
        self.label_2.setText(_translate("Dialog", "Path to file"))
        self.label_5.setText(_translate("Dialog", "Glich quality"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
